name: Continous Integration
on:
  push:
    paths:
      - '**.dart'
      - 'pubspec.yaml'
  pull_request:
    branches: [ master, ]
    paths:
      - '**.dart'
      - 'pubspec.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: 'stable'
          flutter-version: '3.29.x'

      - run: dart --version
      - run: flutter --version

      - name: Install dependencies
        run: |
          sudo apt install libsqlite3-dev lcov
          flutter pub get

      # Removing some folders from the coverage since these files are not really
      # part of the app code and just get in the way of the report
      - name: Test app
        run: |
          flutter test --coverage
          lcov --remove coverage/lcov.info 'lib/l10n/generated/*' 'lib/theme/*' -o coverage/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
